pipeline {
    agent any

    environment {
        SERVER = credentials('ec2-jenkins-server-creds')
    }

    stages {
        /* stage('Checkout') {
            steps {
                git url: 'https://github.com/sudarshana-git/jenkins-basics/',branch: 'main'
                sh "ls -ltr"
            }
        }  */

        stage('Setup') {
            steps {
                /* withCredentials([usernamePassword(credentialsId: 'ec2-jenkins-server-creds', usernameVariable: "myuser", passwordVariable: "mypassword")]) {
                    sh '''
                    echo ${myuser}
                    echo ${mypassword}
                    '''
                }

                echo "my creds: ${SERVER}"
                echo "username: ${SERVER_USR}"
                echo "password: ${SERVER_PSW}" */

                sh "pip install -r 01-jenkins-basics/requirements.txt"
            }
        }

        stage('Test') {
            steps {
                dir('01-jenkins-basics') {
                    sh "pytest"
                }
            }
        }

        stage('Lint and test') {
            steps {
                sh "echo Linting code in the main stage"
                sh "echo Formatting code in the main stage"
            }
        }

        stage('Deployment') {
            input {
                message "Do you want to proceed further?"
                ok "Yes"
            }
            steps {
                echo "Running Deployment"
            }
        }
    }
}